export const queryKeys = {
  tasks: {
    all: () => ["tasks"],
    lists: () => [...queryKeys.tasks.all(), "list"],
    list: (filters) => [...queryKeys.tasks.lists(), filters],
    details: () => [...queryKeys.tasks.all(), "detail"],
    detail: (id) => [...queryKeys.tasks.details(), id],
    comments: () => [...queryKeys.tasks.all(), "comments"],
    comment: (taskId) => [...queryKeys.tasks.comments(), taskId],
  },
  farmTasks: {
    all: () => ["farmTasks"],
    lists: () => [...queryKeys.farmTasks.all(), "list"],
    list: (filters) => [...queryKeys.farmTasks.lists(), filters],
    details: () => [...queryKeys.farmTasks.all(), "detail"],
    detail: (id) => [...queryKeys.farmTasks.details(), id],
    comments: () => [...queryKeys.farmTasks.all(), "comments"],
    comment: (taskId) => [...queryKeys.farmTasks.comments(), taskId],
  },
  dailies: {
    all: () => ["dailies"],
    lists: () => [...queryKeys.dailies.all(), "list"],
    list: (filters) => [...queryKeys.dailies.lists(), filters],
    details: () => [...queryKeys.dailies.all(), "detail"],
    detail: (id) => [...queryKeys.dailies.details(), id],
  },
  meetings: {
    all: () => ["meetings"],
    lists: () => [...queryKeys.meetings.all(), "list"],
    list: (filters) => [...queryKeys.meetings.lists(), filters],
    details: () => [...queryKeys.meetings.all(), "detail"],
    detail: (id) => [...queryKeys.meetings.details(), id],
  },
  vipLeads: {
    all: () => ["vipLeads"],
    lists: () => [...queryKeys.vipLeads.all(), "list"],
    list: (filters) => [...queryKeys.vipLeads.lists(), filters],
    details: () => [...queryKeys.vipLeads.all(), "detail"],
    detail: (id) => [...queryKeys.vipLeads.details(), id],
    requests: () => [...queryKeys.vipLeads.all(), "requests"],
    request: (id) => [...queryKeys.vipLeads.requests(), id],
    comments: () => [...queryKeys.vipLeads.all(), "comments"],
    comment: (requestId) => [...queryKeys.vipLeads.comments(), requestId],
  },
  agreements: {
    all: () => ["agreements"],
    lists: () => [...queryKeys.agreements.all(), "list"],
    list: (filters) => [...queryKeys.agreements.lists(), filters],
    details: () => [...queryKeys.agreements.all(), "detail"],
    detail: (id) => [...queryKeys.agreements.details(), id],
  },
  users: {
    all: () => ["users"],
    lists: () => [...queryKeys.users.all(), "list"],
    list: (filters) => [...queryKeys.users.lists(), filters],
    details: () => [...queryKeys.users.all(), "detail"],
    detail: (id) => [...queryKeys.users.details(), id],
    roles: () => [...queryKeys.users.all(), "roles"],
  },
  leads: {
    all: () => ["leads"],
    lists: () => [...queryKeys.leads.all(), "list"],
    list: (filters) => [...queryKeys.leads.lists(), filters],
    details: () => [...queryKeys.leads.all(), "detail"],
    detail: (id) => [...queryKeys.leads.details(), id],
    comments: () => [...queryKeys.leads.all(), "comments"],
    comment: (leadId) => [...queryKeys.leads.comments(), leadId],
  },
  auth: {
    all: () => ["auth"],
    currentUser: () => [...queryKeys.auth.all(), "currentUser"],
    departments: () => [...queryKeys.auth.all(), "departments"],
  },
  chat: {
    all: () => ["chat"],
    messages: () => [...queryKeys.chat.all(), "messages"],
    message: (id) => [...queryKeys.chat.messages(), id],
  },
  calendar: {
    all: () => ["calendar"],
    events: () => [...queryKeys.calendar.all(), "events"],
    event: (id) => [...queryKeys.calendar.events(), id],
  },
} 